Migrate snekclientv2 aa1 to implement 1
snek-at/front pull request #116
Opened 2020-08-05 23:11 UTC by schettn

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently [SnekClient V2](https://github.com/snek-at/client) is not supported. 😞 

**What is the new behavior (if this is a feature change)?**
- Now  [SnekClient V2](https://github.com/snek-at/client) is supported. 😃 

**Other information**:
- 🐍

2020-08-05 23:17 UTC, schettn commented on src/store/actions/authActions.js
> +          if (!whoami?.anonymous) {
Note to myself..:

What if whoami is undefined?

2020-08-05 23:22 UTC, schettn commented on src/store/actions/authActions.js
> +          if (!whoami?.anonymous) {
![image](https://user-images.githubusercontent.com/52858351/89473351-ebcca880-d782-11ea-8144-d7837b8f2801.png)

This is issue is not urgent cause whoami cannot be undefined.
However we should adjust.

2020-08-05 23:24 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-08-05 23:24 UTC, kleberbaum commented on src/store/actions/authActions.js
> +          if (!whoami?.anonymous) {
This line is absolutely beautiful but probably a bug.

2020-08-06 08:36 UTC, pinterid approved these changes
LGTM

2020-08-06 08:36 UTC, Aichnerc approved these changes
LGTM

2020-08-06 08:40 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-08-06 10:38 UTC, merged