Add heart aa1 to implement 1
snek-at/front pull request #49
Opened 2020-06-06 22:57 UTC by pinterid

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there are no authentication methods. #45 
- Currently there are no registration methods. #46 
- Currently there are no data handling methods. #47 
- Currently there is no fitting site title. #48 

**What is the new behavior (if this is a feature change)?**
- Now there are authentication methods. #45 
- Now there are registration methods. #46 
- Now there are data handling methods. #47 
- Now there is a fitting site title. #48 

**Other information**:
- Ref: 🐍

2020-06-06 23:07 UTC, schettn requested changes
I left some suggestions

2020-06-06 23:07 UTC, schettn commented on public/manifest.json
> +  "short_name": "SNEKp",
```suggestion
  "short_name": "SNEK",
```

2020-06-06 23:07 UTC, schettn commented on src/components/pages/TalkPage/index.jsx
>        if (this.props.match.params) {
```suggestion
      if (this.props.match?.params) {
```

2020-06-06 23:07 UTC, schettn commented on src/components/pages/TalkPage/index.jsx
>            const username = this.props.match.params.username;
Maybe we should declare more variables before the if

2020-06-06 23:07 UTC, schettn commented on src/App.js
> +    const unhashedPassword = registrationData.password;
```suggestion
    let intelData;
    
    const unhashedPassword = registrationData.password;
```

2020-06-06 23:08 UTC, pinterid reviewed
Some changes have to be made.

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Begin Session
```suggestion
   * Begin Session
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Authenticate
```suggestion
   * Authenticate
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Handle login
```suggestion
   * Handle login
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Logout user
```suggestion
   * Logout user
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Fetch GitLab Servers
```suggestion
   * Fetch GitLab Servers
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Append Source Objects
```suggestion
   * Append Source Objects
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Register user
```suggestion
   * Register user
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Get intel data
```suggestion
   * Get intel data
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Get all talks
```suggestion
   * Get all talks
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Upload talk
```suggestion
   * Upload talk
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Delete talk
```suggestion
   * Delete talk
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Get talk
```suggestion
   * Get talk
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Fetch Cache Data
```suggestion
   * Fetch Cache Data
   *
```

2020-06-06 23:08 UTC, pinterid commented on src/App.js
> +   * Save settings
```suggestion
   * Save settings
   *
```

2020-06-06 23:18 UTC, schettn approved these changes
LGTM

2020-06-07 00:35 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-06-07 00:35 UTC, kleberbaum commented on public/index.html
> +    <title>SNEK - Social Network for Engineers and Knowledged</title>
I think it would be better to have a short page title.
```suggestion
    <title>SNEK</title>
```

2020-06-07 00:35 UTC, kleberbaum commented on src/components/molecules/modals/SettingsModal/settings.scss
> +    box-shadow: none;
Please move css property up.
```suggestion
    box-shadow: none;
    
    i {
      padding-left: 0.5rem;
    }
```

2020-06-07 00:41 UTC, pinterid reviewed
Looks good to merge.

2020-06-07 01:09 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-06-07 01:09 UTC, merged